name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Clean build directory
      run: |
        mkdir -p build
        rm -rf build/*
    
    - name: Configure and build
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build .
    
    - name: Test run
      run: |
            cd build
            ./tests/main.cpp

   
