name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Configure and build
      run: |
        cd build
        cmake ..
        cmake --build .
    
    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure
